-- 코드를 입력하세요
SELECT MEMBER_ID, MEMBER_NAME, GENDER, DATE_FORMAT(DATE_OF_BIRTH, '%Y-%m-%d') as DATE_OF_BIRTH from MEMBER_PROFILE 
WHERE (TLNO is not NULL) and 
MONTH(DATE_OF_BIRTH) ='03' and GENDER = 'W';